import Foundation
import NeoAnkiAPI

private enum GeneratorError: Error, CustomStringConvertible {
    case invalidCommand
    case stale(String)

    var description: String {
        switch self {
        case .invalidCommand:
            "Usage: neoanki-api-reference <generate|check>"
        case let .stale(path):
            "Generated API reference is stale or missing: \(path)"
        }
    }
}

private let sourceFile = URL(fileURLWithPath: #filePath).standardizedFileURL
private let repositoryRoot = sourceFile
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()
private let outputRoot = repositoryRoot.appendingPathComponent("docs/api", isDirectory: true)

private struct GeneratedFile {
    let relativePath: String
    let data: Data
}

private func markdownData(_ text: String) -> Data {
    Data((text.hasSuffix("\n") ? text : text + "\n").utf8)
}

private func operationLink(_ group: APIEndpointGroup) -> String {
    "{{ '/api/\(group.slug)/' | relative_url }}"
}

private func schemaLink(_ name: String) -> String {
    "{{ '/api/schemas/#schema-\(slug(name))' | relative_url }}"
}

private func slug(_ value: String) -> String {
    value.unicodeScalars.reduce(into: "") { result, scalar in
        if CharacterSet.alphanumerics.contains(scalar) {
            result.append(Character(String(scalar).lowercased()))
        } else if !result.hasSuffix("-") {
            result.append("-")
        }
    }.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
}

private func indexPage() -> String {
    let groups = APIEndpointGroup.allCases.compactMap { group -> String? in
        let count = APIOpenAPI.endpoints.count { $0.group == group }
        guard count > 0 else { return nil }
        return "- [\(group.rawValue)](\(operationLink(group))) — \(count) operations"
    }.joined(separator: "\n")
    return """
    ---
    title: Local API reference
    description: Generated endpoint and schema reference for the NeoAnki loopback automation API.
    audience: api
    contract_digest: \(APIOpenAPI.contractDigest)
    nav_order: 3
    permalink: /api/
    ---

    # Local API reference

    This reference is generated from the same typed endpoint registry used by
    NeoAnki2 to accept requests and serve `GET /v1/openapi.json`. Pull requests
    cannot merge when the checked-in pages or OpenAPI document differ from the
    current registry.

    The API listens on loopback only and is disabled until enabled in NeoAnki2.
    Start with the [local automation API guide]({{ '/user/local-api/' | relative_url }})
    for pairing and token safety. Internal rationale and release criteria remain
    in the [API design requirements]({{ '/LOCAL_API/' | relative_url }}).

    ## Operations

    \(groups)

    ## Contract files

    - [Schema reference]({{ '/api/schemas/' | relative_url }})
    - [Shared errors]({{ '/api/errors/' | relative_url }})
    - [Download OpenAPI 3.1 JSON]({{ '/api/openapi.json' | relative_url }})

    _Generated by `swift run neoanki-api-reference generate`; do not edit by hand._
    """
}

private func curlExample(for endpoint: APIEndpointDefinition) -> String {
    var lines = ["curl --request \(endpoint.method.rawValue) \\",
                 "  'http://127.0.0.1:8766\(endpoint.pathTemplate)' \\"]
    if endpoint.requiredScope != nil {
        lines.append("  --header 'Authorization: Bearer <token>'" +
            (endpoint.acceptsRequestBody ? " \\" : ""))
    }
    if endpoint.acceptsRequestBody {
        lines.append("  --header 'Content-Type: application/json' \\")
        lines.append("  --data '<request-json>'")
    }
    return lines.joined(separator: "\n")
}

private func groupPage(_ group: APIEndpointGroup) -> String {
    let endpoints = APIOpenAPI.endpoints
        .filter { $0.group == group }
        .sorted {
            if $0.pathTemplate != $1.pathTemplate { return $0.pathTemplate < $1.pathTemplate }
            return $0.method.rawValue < $1.method.rawValue
        }
    var output = """
    ---
    title: \(group.rawValue)
    description: Generated NeoAnki local API operations for \(group.rawValue.lowercased()).
    audience: api
    contract_digest: \(APIOpenAPI.contractDigest)
    parent: Local API reference
    permalink: /api/\(group.slug)/
    ---

    # \(group.rawValue)

    [API reference]({{ '/api/' | relative_url }}) · [OpenAPI JSON]({{ '/api/openapi.json' | relative_url }})

    """
    for endpoint in endpoints {
        output += """

        ## `\(endpoint.method.rawValue) \(endpoint.pathTemplate)`

        \(endpoint.description)

        - **Operation ID:** `\(endpoint.operationID)`
        - **Authorization:** \(endpoint.requiredScope.map { "Bearer token with `\($0)`" } ?? "Public loopback operation")
        - **Success:** `\(endpoint.successStatus)`\(endpoint.responseSchema.map { " with [\($0)](\(schemaLink($0)))" } ?? " with no response body")
        - **Request body:** \(endpoint.requestSchema.map { "[\($0)](\(schemaLink($0)))" } ?? "None")
        - **Success headers:** \(endpoint.successHeaders.isEmpty ? "None" : endpoint.successHeaders.map { "`\($0)`" }.joined(separator: ", "))
        - **Errors:** \(endpoint.errorResponses.map { "`\($0)`" }.joined(separator: ", ")) using the [shared problem format]({{ '/api/errors/' | relative_url }})
        """
        if !endpoint.parameters.isEmpty {
            output += "\n\n### Parameters\n"
            for parameter in endpoint.parameters {
                output += "\n- `\(parameter.name)` — \(parameter.location); "
                    + (parameter.isRequired ? "required" : "optional")
                    + ". \(parameter.description)"
            }
        }
        output += """


        ### Example request

        ```bash
        \(curlExample(for: endpoint))
        ```
        """
    }
    return output + "\n\nContract digest: `\(APIOpenAPI.contractDigest)`.\n\n_Generated from the runtime endpoint registry; do not edit by hand._\n"
}

private func typeDescription(_ schema: Any) -> String {
    guard let dictionary = schema as? [String: Any] else { return "value" }
    if let reference = dictionary["$ref"] as? String {
        return reference.split(separator: "/").last.map(String.init) ?? "referenced value"
    }
    if let oneOf = dictionary["oneOf"] as? [Any] {
        return oneOf.map(typeDescription).joined(separator: " or ")
    }
    if let type = dictionary["type"] as? String {
        if type == "array", let items = dictionary["items"] {
            return "array of \(typeDescription(items))"
        }
        return type
    }
    if let types = dictionary["type"] as? [String] {
        return types.joined(separator: " or ")
    }
    return "object"
}

private func schemasPage(openAPI: [String: Any]) -> String {
    let components = openAPI["components"] as? [String: Any]
    let schemas = components?["schemas"] as? [String: Any] ?? [:]
    var output = """
    ---
    title: API schemas
    description: Generated request and response schemas for the NeoAnki local API.
    audience: api
    contract_digest: \(APIOpenAPI.contractDigest)
    parent: Local API reference
    permalink: /api/schemas/
    ---

    # API schemas

    [API reference]({{ '/api/' | relative_url }}) · [OpenAPI JSON]({{ '/api/openapi.json' | relative_url }})
    """
    for name in schemas.keys.sorted() {
        guard let schema = schemas[name] as? [String: Any] else { continue }
        output += "\n\n## \(name) {#schema-\(slug(name))}\n\n"
        output += "Type: **\(typeDescription(schema))**."
        let required = Set(schema["required"] as? [String] ?? [])
        if let properties = schema["properties"] as? [String: Any], !properties.isEmpty {
            output += "\n\n### Properties\n"
            for property in properties.keys.sorted() {
                output += "\n- `\(property)` — \(typeDescription(properties[property] as Any)); "
                    + (required.contains(property) ? "required" : "optional")
            }
        }
    }
    return output + "\n\nContract digest: `\(APIOpenAPI.contractDigest)`.\n\n_Generated from the runtime schema catalog; do not edit by hand._\n"
}

private func errorsPage() -> String {
    """
    ---
    title: API errors
    description: Shared problem-details response format and recovery categories for the NeoAnki local API.
    audience: api
    contract_digest: \(APIOpenAPI.contractDigest)
    parent: Local API reference
    permalink: /api/errors/
    ---

    # API errors

    Every unsuccessful operation returns `application/problem+json` using the
    [Problem schema]({{ '/api/schemas/#schema-problem' | relative_url }}).

    - `400` — malformed input, unsupported query members, or validation failure.
    - `401` — missing or invalid bearer token.
    - `403` — loopback, origin, pairing, or scope policy rejected the request.
    - `404` — no registered operation or visible resource matches the request.
    - `409` — revision, idempotency, or state transition conflict.
    - `412` — `If-Match` or confirmation precondition failed.
    - `413` — request body exceeds its endpoint limit.
    - `422` — the request is syntactically valid but cannot be applied.
    - `500` — unexpected internal failure; record the returned `requestId`.

    See the [API design requirements]({{ '/LOCAL_API/#64-errors' | relative_url }})
    for normative security and retry semantics.

    Contract digest: `\(APIOpenAPI.contractDigest)`.
    """
}

private func generatedFiles() throws -> [GeneratedFile] {
    let openAPIObject = try JSONSerialization.jsonObject(with: APIOpenAPI.document)
    guard let openAPI = openAPIObject as? [String: Any] else {
        throw GeneratorError.stale("APIOpenAPI.document")
    }
    var files = [
        GeneratedFile(relativePath: "index.md", data: markdownData(indexPage())),
        GeneratedFile(relativePath: "schemas.md", data: markdownData(schemasPage(openAPI: openAPI))),
        GeneratedFile(relativePath: "errors.md", data: markdownData(errorsPage())),
        GeneratedFile(relativePath: "openapi.json", data: APIOpenAPI.document),
    ]
    files += APIEndpointGroup.allCases.compactMap { group in
        guard APIOpenAPI.endpoints.contains(where: { $0.group == group }) else { return nil }
        return GeneratedFile(
            relativePath: "groups/\(group.slug).md",
            data: markdownData(groupPage(group))
        )
    }
    return files
}

private func generate(_ files: [GeneratedFile]) throws {
    for file in files {
        let destination = outputRoot.appendingPathComponent(file.relativePath)
        try FileManager.default.createDirectory(
            at: destination.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try file.data.write(to: destination, options: .atomic)
    }
}

private func check(_ files: [GeneratedFile]) throws {
    for file in files {
        let destination = outputRoot.appendingPathComponent(file.relativePath)
        guard let existing = try? Data(contentsOf: destination), existing == file.data else {
            throw GeneratorError.stale("docs/api/\(file.relativePath)")
        }
    }
}

do {
    let command = CommandLine.arguments.dropFirst().first
    let files = try generatedFiles()
    switch command {
    case "generate":
        try generate(files)
        print("Generated \(files.count) API reference files for \(APIOpenAPI.endpoints.count) operations.")
    case "check":
        try check(files)
        print("API reference is current (\(APIOpenAPI.endpoints.count) operations).")
    default:
        throw GeneratorError.invalidCommand
    }
} catch {
    fputs("error: \(error)\n", stderr)
    exit(1)
}
