import NeoAnkiCore
import SwiftUI

struct TemplateEditorView: View {
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @Bindable var model: TemplatesModel
    let itemType: ItemType
    let editingTemplate: Template?
    var onDismiss: () -> Void = {}

    @State private var editor: TemplateEditorState
    @State private var compactSheet: CompactSheet?
    @State private var showDiscardConfirmation = false
    @State private var showDeleteConfirmation = false
    @State private var affectedResponseCount = 0
    @State private var isCompactLayout = false
    @FocusState private var validationFocus: TemplateValidationTarget?

    private enum CompactSheet: String, Identifiable {
        case ingredients, inspector
        var id: String { rawValue }
    }

    init(
        model: TemplatesModel,
        itemType: ItemType,
        editingTemplate: Template? = nil,
        onDismiss: @escaping () -> Void = {}
    ) {
        self.model = model
        self.itemType = itemType
        self.editingTemplate = editingTemplate
        self.onDismiss = onDismiss
        _editor = State(initialValue: TemplateEditorState(
            itemType: itemType,
            editingTemplate: editingTemplate
        ))
    }

    var body: some View {
        @Bindable var editor = editor
        GeometryReader { geometry in
            VStack(spacing: 0) {
                builderHeader
                Divider()
                if geometry.size.width >= 900 {
                    HSplitView {
                        TemplateIngredientsPane(editor: editor)
                            .frame(minWidth: 220, idealWidth: 250, maxWidth: 290)
                        TemplateStudyPreviewPane(editor: editor, validationFocus: $validationFocus)
                            .frame(minWidth: 420, maxWidth: .infinity)
                            .layoutPriority(1)
                        TemplateInspectorPane(editor: editor, validationFocus: $validationFocus)
                            .frame(minWidth: 260, idealWidth: 290, maxWidth: 340)
                    }
                } else {
                    TemplateStudyPreviewPane(editor: editor, validationFocus: $validationFocus)
                }
            }
            .background(DesignSystem.detailBackground)
            .onAppear { isCompactLayout = geometry.size.width < 900 }
            .onChange(of: geometry.size.width) { _, width in
                isCompactLayout = width < 900
            }
        }
        .navigationTitle(editingTemplate == nil ? "Add Template" : "Edit Template")
        .toolbar { toolbar }
        .sheet(item: $compactSheet) { sheet in
            NavigationStack {
                Group {
                    switch sheet {
                    case .ingredients: TemplateIngredientsPane(editor: editor)
                    case .inspector: TemplateInspectorPane(editor: editor, validationFocus: $validationFocus)
                    }
                }
                .frame(minWidth: 340, minHeight: 480)
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Done") { compactSheet = nil }
                    }
                }
            }
        }
        .confirmationDialog(
            "Discard template changes?",
            isPresented: $showDiscardConfirmation,
            titleVisibility: .visible
        ) {
            Button("Discard Changes", role: .destructive) { onDismiss() }
                .accessibilityIdentifier("confirmDiscardTemplate")
            Button("Keep Editing", role: .cancel) {}
                .accessibilityIdentifier("cancelDiscardTemplate")
        } message: {
            Text("Your unsaved template changes will be lost.")
        }
        .confirmationDialog(
            "Delete this template?",
            isPresented: $showDeleteConfirmation,
            titleVisibility: .visible
        ) {
            Button("Delete Template", role: .destructive) { Task { await deleteTemplate() } }
                .accessibilityIdentifier("confirmDeleteTemplate")
            Button("Cancel", role: .cancel) {}
                .accessibilityIdentifier("cancelDeleteTemplate")
        } message: {
            if affectedResponseCount > 0 {
                Text("Cards generated by this template and \(affectedResponseCount) saved spoken \(affectedResponseCount == 1 ? "response" : "responses") will be permanently deleted.")
            } else {
                Text("Cards generated by this template may be removed. This action cannot be undone.")
            }
        }
        .confirmationDialog(
            "Clear the answer side?",
            isPresented: Binding(
                get: { editor.pendingInteraction == .audioSubmission },
                set: { if !$0 { editor.cancelPendingInteraction() } }
            ),
            titleVisibility: .visible
        ) {
            Button("Clear Answer and Continue", role: .destructive) {
                editor.confirmPendingInteraction()
            }
            .accessibilityIdentifier("confirmAudioSubmission")
            Button("Cancel", role: .cancel) { editor.cancelPendingInteraction() }
        } message: {
            Text("Audio Submission cards are prompt-only. The current answer is kept temporarily and restored if you switch back before saving.")
        }
    }

    private var builderHeader: some View {
        VStack(alignment: .leading, spacing: DesignSystem.Spacing.xs) {
            HStack(alignment: .firstTextBaseline, spacing: DesignSystem.Spacing.md) {
                TextField("Template name", text: $editor.draft.name)
                    .textFieldStyle(.plain)
                    .font(DesignSystem.Typography.uiTitle)
                    .focused($validationFocus, equals: .name)
                    .accessibilityLabel("Template name")
                    .accessibilityIdentifier("templateNameField")
                Picker("Interaction", selection: interactionBinding) {
                    ForEach(Interaction.allCases, id: \.self) { value in
                        Text(value.label).tag(value)
                    }
                }
                .labelsHidden()
                .frame(width: 190)
                .accessibilityLabel("Interaction")
                .accessibilityIdentifier("templateInteractionPicker")
            }
            if let issue = editor.issue(for: .name) { ValidationMessage(issue.message) }
            if editor.draft.interaction == .audioSubmission {
                Label(
                    "Spoken responses stay on this device and are not included in cloud sync.",
                    systemImage: "lock.fill"
                )
                .font(DesignSystem.Typography.uiHint)
                .foregroundStyle(.secondary)
            }
            if let first = editor.validationIssues.first { ErrorBanner(message: first.message) }
        }
        .padding(.horizontal, DesignSystem.Spacing.lg)
        .padding(.vertical, DesignSystem.Spacing.sm)
        .controlSize(.large)
    }

    private var interactionBinding: Binding<Interaction> {
        Binding(
            get: { editor.draft.interaction },
            set: { value in editor.requestInteraction(value) }
        )
    }

    @ToolbarContentBuilder
    private var toolbar: some ToolbarContent {
        ToolbarItem(placement: .cancellationAction) {
            Button("Cancel") { requestDismissal() }
                .keyboardShortcut(.cancelAction)
                .accessibilityIdentifier("cancelTemplateEditor")
        }
        if isCompactLayout {
            ToolbarItemGroup {
                Button("Ingredients", systemImage: "square.grid.2x2") { compactSheet = .ingredients }
                    .accessibilityIdentifier("templateIngredientsToolbar")
                Button("Inspector", systemImage: "slider.horizontal.3") { compactSheet = .inspector }
                    .accessibilityIdentifier("templateInspectorToolbar")
            }
        }
        if editingTemplate != nil {
            ToolbarItem {
                Menu("More", systemImage: "ellipsis.circle") {
                    Button("Delete Template", systemImage: "trash", role: .destructive) {
                        prepareTemplateDeletion()
                    }
                    .accessibilityIdentifier("deleteTemplate")
                }
                .accessibilityIdentifier("templateMoreMenu")
            }
        }
        ToolbarItem(placement: .confirmationAction) {
            Button(editor.isSaving ? "Saving…" : "Save") { Task { await save() } }
                .buttonStyle(.borderedProminent)
                .keyboardShortcut(.defaultAction)
                .disabled(editor.isSaving)
                .accessibilityIdentifier("saveTemplate")
                // Keep the prominent hit target inside short CI and compact
                // macOS toolbar bounds instead of letting its trailing edge clip.
                .padding(.trailing, DesignSystem.Spacing.md)
        }
    }

    private func save() async {
        guard editor.validate() else {
            let target = editor.validationIssues.first?.target
            if isCompactLayout, target == .generation { compactSheet = .inspector }
            validationFocus = target
            return
        }
        editor.isSaving = true
        defer { editor.isSaving = false }
        if await model.saveTemplate(editor.draft, editingID: editingTemplate?.id) { onDismiss() }
    }

    private func deleteTemplate() async {
        guard let editingTemplate else { return }
        if await model.deleteTemplate(id: editingTemplate.id) { onDismiss() }
    }

    private func prepareTemplateDeletion() {
        guard let editingTemplate else { return }
        Task {
            affectedResponseCount = (try? await model.studyResponseCount(templateID: editingTemplate.id)) ?? 0
            showDeleteConfirmation = true
        }
    }

    private func requestDismissal() {
        if editor.isDirty { showDiscardConfirmation = true } else { onDismiss() }
    }
}

private struct TemplateIngredientsPane: View {
    @Bindable var editor: TemplateEditorState

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: DesignSystem.Spacing.md) {
                Text("Card Ingredients").font(DesignSystem.Typography.uiSection)
                Text("Drag a block into the card, or use its Add menu.")
                    .font(DesignSystem.Typography.uiHint).foregroundStyle(.secondary)
                ForEach(editor.itemType.fields) { field in
                    ingredient(
                        title: field.name,
                        detail: FieldTypeLabels.name(for: field.type),
                        icon: field.type.icon,
                        payload: .init(source: .field(field.id)),
                        add: { editor.addField(field.id, to: $0) }
                    )
                }
                ingredient(
                    title: "Literal Text",
                    detail: "A fixed label or instruction",
                    icon: "text.quote",
                    payload: .init(source: .literal),
                    add: { editor.addLiteral(to: $0) }
                )
            }
            .padding(DesignSystem.Spacing.md)
        }
        .background(DesignSystem.sidebarBackground)
        .controlSize(.large)
        .accessibilityIdentifier("templateIngredientsPane")
    }

    private func ingredient(
        title: String,
        detail: String,
        icon: String,
        payload: TemplateBuilderDragPayload,
        add: @escaping (TemplateSide) -> Void
    ) -> some View {
        HStack(spacing: DesignSystem.Spacing.sm) {
            Image(systemName: icon).frame(width: 22).accessibilityHidden(true)
            VStack(alignment: .leading, spacing: 2) {
                Text(title).font(.body.weight(.medium))
                Text(detail).font(.caption).foregroundStyle(.secondary)
            }
            Spacer()
            Menu("Add", systemImage: "plus") {
                Button("Add to Prompt") { add(.prompt) }
                Button("Add to Answer") { add(.answer) }
                    .disabled(editor.draft.interaction == .audioSubmission)
            }
            .labelStyle(.iconOnly)
            .accessibilityLabel("Add \(title)")
        }
        .padding(DesignSystem.Spacing.sm)
        .frame(minHeight: 44)
        .background(.background, in: RoundedRectangle(cornerRadius: 8))
        .draggable(payload)
        .accessibilityElement(children: .contain)
    }
}

private struct TemplateStudyPreviewPane: View {
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @Bindable var editor: TemplateEditorState
    @FocusState.Binding var validationFocus: TemplateValidationTarget?

    var body: some View {
        ScrollView {
            VStack(spacing: DesignSystem.Spacing.lg) {
                HStack {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Study Preview").font(DesignSystem.Typography.uiSection)
                        Text("Example content only — no library items or media are loaded.")
                            .font(DesignSystem.Typography.uiHint).foregroundStyle(.secondary)
                    }
                    Spacer()
                    Picker("Preview phase", selection: $editor.previewPhase) {
                        ForEach(TemplatePreviewPhase.allCases, id: \.self) { Text($0.label).tag($0) }
                    }
                    .pickerStyle(.segmented)
                    .labelsHidden()
                    .frame(maxWidth: 260, minHeight: 44)
                    .accessibilityIdentifier("templatePreviewPhase")
                }
                VStack(spacing: DesignSystem.Spacing.lg) {
                    side(.prompt)
                    if TemplatePreviewFixture.sides(
                        for: editor.previewPhase,
                        interaction: editor.draft.interaction
                    ).contains(.answer) {
                        Divider()
                        side(.answer).transition(.opacity)
                    }
                    responseSimulation
                }
                .padding(DesignSystem.Spacing.xl)
                .frame(maxWidth: 680, minHeight: 400)
                .background(.background, in: RoundedRectangle(cornerRadius: 16))
                .overlay(RoundedRectangle(cornerRadius: 16).stroke(.separator))
                Button {
                    let action = { editor.previewPhase = editor.previewPhase == .beforeAnswer ? .afterAnswer : .beforeAnswer }
                    if reduceMotion { action() } else { withAnimation(.easeOut(duration: 0.18), action) }
                } label: {
                    Label(
                        editor.previewPhase == .beforeAnswer ? "Show Answer" : "Show Prompt",
                        systemImage: editor.previewPhase == .beforeAnswer ? "eye" : "arrow.uturn.backward"
                    ).frame(minHeight: 32)
                }
                .buttonStyle(.borderedProminent)
                .disabled(editor.draft.interaction == .audioSubmission && editor.previewPhase == .beforeAnswer)
                .accessibilityIdentifier("templateShowAnswer")
            }
            .padding(DesignSystem.Spacing.lg)
            .frame(maxWidth: .infinity)
        }
        .background(DesignSystem.detailBackground)
        .accessibilityIdentifier("templateStudyPreviewPane")
    }

    @ViewBuilder
    private func side(_ side: TemplateSide) -> some View {
        let slots = editor.slots(on: side)
        VStack(spacing: DesignSystem.Spacing.sm) {
            HStack {
                Text(side.title.uppercased()).font(.caption.weight(.semibold)).foregroundStyle(.secondary)
                Spacer()
                Menu("Add \(side.title)", systemImage: "plus") {
                    ForEach(editor.itemType.fields) { field in
                        Button(field.name) { editor.addField(field.id, to: side) }
                    }
                    Divider()
                    Button("Literal Text") { editor.addLiteral(to: side) }
                }
                .disabled(side == .answer && editor.draft.interaction == .audioSubmission)
                .accessibilityIdentifier(side == .prompt ? "templatePromptField" : "templateAnswerField")
            }
            if slots.isEmpty {
                TemplateSideDropZone(editor: editor, side: side, validationFocus: $validationFocus)
            } else {
                ForEach(slots) { slot in
                    TemplatePreviewBlock(
                        editor: editor,
                        side: side,
                        slot: slot,
                        validationFocus: $validationFocus
                    )
                }
                TemplateSideDropZone(
                    editor: editor,
                    side: side,
                    compact: true,
                    validationFocus: $validationFocus
                )
            }
            if let issue = editor.issue(for: .side(side)) { ValidationMessage(issue.message) }
        }
        .accessibilityElement(children: .contain)
        .accessibilityLabel("\(side.title) card composition")
    }

    @ViewBuilder
    private var responseSimulation: some View {
        switch editor.draft.interaction {
        case .type:
            TextField("Type your answer", text: .constant(""))
                .disabled(true).accessibilityHint("Preview only")
        case .choose:
            HStack { ForEach(["Option A", "Option B", "Option C"], id: \.self) { Text($0).padding(8).background(.quaternary, in: Capsule()) } }
        case .record, .audioSubmission:
            Label("Recording control preview", systemImage: "mic.circle")
                .foregroundStyle(.secondary)
                .accessibilityHint("Illustrative only. Microphone access is not requested.")
        case .arrange:
            Label("Arrangement controls appear during study", systemImage: "arrow.up.arrow.down")
                .foregroundStyle(.secondary)
        case .reveal, .cloze: EmptyView()
        }
    }
}

private struct TemplateSideDropZone: View {
    @Bindable var editor: TemplateEditorState
    let side: TemplateSide
    var compact = false
    @FocusState.Binding var validationFocus: TemplateValidationTarget?
    @State private var isTargeted = false

    var body: some View {
        Text(compact ? "Drop another block" : "Drop a field or Literal Text here")
            .font(DesignSystem.Typography.uiHint)
            .foregroundStyle(isTargeted ? DesignSystem.accent : .secondary)
            .frame(maxWidth: .infinity, minHeight: compact ? 44 : 96)
            .background(isTargeted ? DesignSystem.accent.opacity(0.12) : Color.secondary.opacity(0.06), in: RoundedRectangle(cornerRadius: 10))
            .overlay(RoundedRectangle(cornerRadius: 10).strokeBorder(style: StrokeStyle(lineWidth: 1, dash: [5])).foregroundStyle(isTargeted ? DesignSystem.accent : Color.secondary))
            .dropDestination(for: TemplateBuilderDragPayload.self) { payloads, _ in
                payloads.first.map { editor.accept($0, on: side) } ?? false
            } isTargeted: { isTargeted = $0 }
            .focusable()
            .focused($validationFocus, equals: .side(side))
            .accessibilityIdentifier("template\(side.title)DropZone")
    }
}

private struct TemplatePreviewBlock: View {
    @Bindable var editor: TemplateEditorState
    let side: TemplateSide
    let slot: SlotDraft
    @FocusState.Binding var validationFocus: TemplateValidationTarget?

    var body: some View {
        Button { editor.selection = .slot(side: side, id: slot.id) } label: {
            Group {
                if let value = TemplatePreviewFixture.value(for: slot, in: editor.itemType) {
                    ContentValueView(
                        value: value,
                        presentation: Presentation(reveal: slot.reveal, media: slot.media),
                        isAnswerRevealed: TemplatePreviewFixture.isAnswerRevealed(
                            for: editor.previewPhase
                        )
                    )
                } else {
                    Label(slot.sourceKind == .literal ? "Enter literal text" : "Choose a field", systemImage: "exclamationmark.circle")
                        .foregroundStyle(.secondary)
                }
            }
            .frame(maxWidth: .infinity, minHeight: 44)
            .padding(DesignSystem.Spacing.sm)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
        .focused($validationFocus, equals: .slot(side: side, id: slot.id))
        .background(isSelected ? DesignSystem.accent.opacity(0.12) : Color.secondary.opacity(0.05), in: RoundedRectangle(cornerRadius: 10))
        .overlay(RoundedRectangle(cornerRadius: 10).stroke(isSelected ? DesignSystem.accent : .clear, lineWidth: 2))
        .draggable(TemplateBuilderDragPayload(source: .slot(side: side, id: slot.id)))
        .contextMenu {
            Button("Move Up") { editor.moveSlot(on: side, id: slot.id, by: -1) }
            Button("Move Down") { editor.moveSlot(on: side, id: slot.id, by: 1) }
            Button("Duplicate") { editor.duplicateSlot(on: side, id: slot.id) }
            Button("Remove", role: .destructive) { editor.removeSlot(on: side, id: slot.id) }
        }
        .accessibilityLabel("\(slotName), \(side.title) block")
        .accessibilityHint("Selects this block for editing. Actions are also available in the Inspector.")
        .accessibilityIdentifier("\(side.rawValue)SlotBlock-\(slot.id)")
    }

    private var isSelected: Bool { editor.selection == .slot(side: side, id: slot.id) }
    private var slotName: String {
        if slot.sourceKind == .literal { return slot.literal.isEmpty ? "Literal Text" : slot.literal }
        return slot.fieldID.flatMap(editor.itemType.field)?.name ?? "Unassigned field"
    }
}

private struct TemplateInspectorPane: View {
    @Bindable var editor: TemplateEditorState
    @FocusState.Binding var validationFocus: TemplateValidationTarget?

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: DesignSystem.Spacing.md) {
                Text("Inspector").font(DesignSystem.Typography.uiSection)
                Button { editor.selection = .generationAndSkill } label: {
                    HStack {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("Generation & Skill").font(.body.weight(.medium))
                            Text(editor.draft.generateWhen == nil ? "All items · \(editor.draft.usesAutomaticSkill ? "Automatic skill" : "Custom skill")" : "Conditional · \(editor.draft.usesAutomaticSkill ? "Automatic skill" : "Custom skill")")
                                .font(.caption).foregroundStyle(.secondary)
                        }
                        Spacer(); Image(systemName: "chevron.right").foregroundStyle(.secondary)
                    }
                    .padding(DesignSystem.Spacing.sm).contentShape(Rectangle())
                }
                .buttonStyle(.plain)
                .focused($validationFocus, equals: .generation)
                .background(editor.selection == .generationAndSkill ? DesignSystem.accent.opacity(0.12) : Color.secondary.opacity(0.06), in: RoundedRectangle(cornerRadius: 8))
                .accessibilityValue(editor.selection == .generationAndSkill ? "Expanded" : "Collapsed")
                .accessibilityIdentifier("templateAdvancedSettings")
                Divider()
                switch editor.selection {
                case let .slot(side, id):
                    if editor.slot(on: side, id: id) != nil {
                        TemplateSlotInspector(editor: editor, side: side, id: id)
                    } else { inspectorEmpty }
                case .generationAndSkill: TemplateGenerationInspector(editor: editor)
                case nil: inspectorEmpty
                }
            }
            .padding(DesignSystem.Spacing.md)
        }
        .background(DesignSystem.sidebarBackground)
        .accessibilityIdentifier("templateInspectorPane")
    }

    private var inspectorEmpty: some View {
        ContentUnavailableView("Select a block", systemImage: "square.dashed", description: Text("Choose a card block to edit its source and presentation."))
    }
}

private struct TemplateSlotInspector: View {
    @Bindable var editor: TemplateEditorState
    let side: TemplateSide
    let id: UUID

    var body: some View {
        if let slot = editor.slot(on: side, id: id) {
            VStack(alignment: .leading, spacing: DesignSystem.Spacing.sm) {
                Text("\(side.title) Block").font(.headline)
                Picker("Source", selection: sourceKind) {
                    Text("Field").tag(SlotDraft.SourceKind.field)
                    Text("Literal text").tag(SlotDraft.SourceKind.literal)
                }
                .accessibilityIdentifier("\(side.rawValue)SlotSource")
                if slot.sourceKind == .field {
                    Picker("Field", selection: fieldID) {
                        Text("Choose field").tag(UUID?.none)
                        ForEach(editor.itemType.fields) { Text($0.name).tag(Optional($0.id)) }
                    }
                } else {
                    TextField("Literal text", text: binding(\.literal), axis: .vertical)
                        .accessibilityIdentifier("\(side.rawValue)SlotLiteral")
                }
                Picker("Reveal", selection: binding(\.reveal)) {
                    ForEach(RevealMode.allCases, id: \.self) { Text($0.label).tag($0) }
                }
                .accessibilityIdentifier("\(side.rawValue)SlotReveal")
                let media = supportedMedia(for: slot)
                if media.count > 1 {
                    Picker("Media", selection: binding(\.media)) {
                        ForEach(media, id: \.self) { Text($0.label).tag($0) }
                    }
                    .accessibilityIdentifier("\(side.rawValue)SlotMedia")
                }
                Picker("Placement", selection: placement) {
                    Text("Prompt").tag(TemplateSide.prompt)
                    Text("Answer").tag(TemplateSide.answer)
                }
                .disabled(editor.draft.interaction == .audioSubmission)
                if let issue = editor.issue(for: .slot(side: side, id: id)) { ValidationMessage(issue.message) }
                Divider()
                HStack {
                    Button("Move Up", systemImage: "arrow.up") { editor.moveSlot(on: side, id: id, by: -1) }
                        .disabled(editor.slots(on: side).first?.id == id)
                    Button("Move Down", systemImage: "arrow.down") { editor.moveSlot(on: side, id: id, by: 1) }
                        .disabled(editor.slots(on: side).last?.id == id)
                }
                Button("Duplicate", systemImage: "plus.square.on.square") { editor.duplicateSlot(on: side, id: id) }
                Button("Remove", systemImage: "trash", role: .destructive) { editor.removeSlot(on: side, id: id) }
            }
            .controlSize(.large)
        }
    }

    private func binding<Value>(_ path: WritableKeyPath<SlotDraft, Value>) -> Binding<Value> {
        Binding(
            get: { editor.slot(on: side, id: id)![keyPath: path] },
            set: { value in editor.updateSlot(on: side, id: id) { $0[keyPath: path] = value } }
        )
    }

    private var sourceKind: Binding<SlotDraft.SourceKind> {
        Binding(
            get: { editor.slot(on: side, id: id)?.sourceKind ?? .field },
            set: { editor.setSourceKind($0, on: side, id: id) }
        )
    }

    private var fieldID: Binding<UUID?> {
        Binding(
            get: { editor.slot(on: side, id: id)?.fieldID },
            set: { editor.setField($0, on: side, id: id) }
        )
    }

    private var placement: Binding<TemplateSide> {
        Binding(get: { side }, set: { destination in
            guard destination != side else { return }
            _ = editor.accept(.init(source: .slot(side: side, id: id)), on: destination)
        })
    }

    private func supportedMedia(for slot: SlotDraft) -> [MediaBehavior] {
        guard slot.sourceKind == .field else { return [.default] }
        return MediaBehavior.supported(for: slot.fieldID.flatMap(editor.itemType.field)?.type.mediaKind)
    }

}

private struct TemplateGenerationInspector: View {
    @Bindable var editor: TemplateEditorState

    var body: some View {
        VStack(alignment: .leading, spacing: DesignSystem.Spacing.sm) {
            Text("Generation & Skill").font(.headline)
            if editor.draft.interaction != .audioSubmission {
                Toggle("Derive skill from the first prompt and answer fields", isOn: $editor.draft.usesAutomaticSkill)
                    .accessibilityIdentifier("templateAutomaticSkill")
            }
            if !editor.draft.usesAutomaticSkill || editor.draft.interaction == .audioSubmission {
                Picker("Input", selection: $editor.draft.skill.input) {
                    ForEach(Modality.allCases, id: \.self) { Text($0.label).tag($0) }
                }.accessibilityIdentifier("templateSkillInput")
                if editor.draft.interaction == .audioSubmission {
                    LabeledContent("Output", value: "Audio")
                } else {
                    Picker("Output", selection: $editor.draft.skill.output) {
                        ForEach(Modality.allCases, id: \.self) { Text($0.label).tag($0) }
                    }.accessibilityIdentifier("templateSkillOutput")
                }
                Picker("Operation", selection: $editor.draft.skill.operation) {
                    ForEach(NeoAnkiCore.Operation.allCases, id: \.self) { Text($0.label).tag($0) }
                }.accessibilityIdentifier("templateSkillOperation")
            }
            Divider()
            Toggle("Only generate this card when…", isOn: generationEnabled)
                .accessibilityIdentifier("templateGenerateCondition")
            if editor.draft.generateWhen != nil {
                ConditionEditor(condition: generationRule, fields: editor.itemType.fields)
            }
            if let issue = editor.issue(for: .generation) { ValidationMessage(issue.message) }
        }
        .controlSize(.large)
    }

    private var generationEnabled: Binding<Bool> {
        Binding(get: { editor.draft.generateWhen != nil }, set: {
            editor.draft.generateWhen = $0 ? .fieldNotEmpty(editor.itemType.fields.first?.id) : nil
        })
    }
    private var generationRule: Binding<ConditionDraft> {
        Binding(
            get: { editor.draft.generateWhen ?? .fieldNotEmpty(editor.itemType.fields.first?.id) },
            set: { editor.draft.generateWhen = $0 }
        )
    }
}

private struct ConditionEditor: View {
    private enum Kind: String, CaseIterable { case fieldNotEmpty, fieldEmpty, all, any }
    @Binding var condition: ConditionDraft
    let fields: [FieldDef]

    var body: some View {
        VStack(alignment: .leading, spacing: DesignSystem.Spacing.xs) {
            Picker("Rule", selection: kind) {
                Text("Field is not empty").tag(Kind.fieldNotEmpty)
                Text("Field is empty").tag(Kind.fieldEmpty)
                Text("All rules match").tag(Kind.all)
                Text("Any rule matches").tag(Kind.any)
            }
            switch condition {
            case .fieldNotEmpty, .fieldEmpty:
                Picker("Field", selection: field) {
                    Text("Choose field").tag(UUID?.none)
                    ForEach(fields) { Text($0.name).tag(Optional($0.id)) }
                }
            case let .all(children), let .any(children):
                ForEach(children.indices, id: \.self) { index in
                    HStack(alignment: .top) {
                        ConditionEditor(condition: child(index), fields: fields)
                        Button("Remove Rule", systemImage: "minus.circle", role: .destructive) { remove(index) }
                            .labelStyle(.iconOnly)
                    }.padding(.leading, DesignSystem.Spacing.sm)
                }
                Button("Add Rule", systemImage: "plus") { add() }
            }
        }
    }

    private var kind: Binding<Kind> { Binding(get: {
        switch condition { case .fieldNotEmpty: .fieldNotEmpty; case .fieldEmpty: .fieldEmpty; case .all: .all; case .any: .any }
    }, set: { value in
        let id = fields.first?.id
        switch value { case .fieldNotEmpty: condition = .fieldNotEmpty(id); case .fieldEmpty: condition = .fieldEmpty(id); case .all: condition = .all([.fieldNotEmpty(id)]); case .any: condition = .any([.fieldNotEmpty(id)]) }
    }) }
    private var field: Binding<UUID?> { Binding(get: {
        switch condition { case let .fieldNotEmpty(id), let .fieldEmpty(id): id; default: nil }
    }, set: { id in
        switch condition { case .fieldNotEmpty: condition = .fieldNotEmpty(id); case .fieldEmpty: condition = .fieldEmpty(id); default: break }
    }) }
    private func child(_ index: Int) -> Binding<ConditionDraft> { Binding(get: {
        switch condition { case let .all(values), let .any(values): values[index]; default: .fieldNotEmpty(fields.first?.id) }
    }, set: { value in
        switch condition { case .all(var values): values[index] = value; condition = .all(values); case .any(var values): values[index] = value; condition = .any(values); default: break }
    }) }
    private func add() {
        let value = ConditionDraft.fieldNotEmpty(fields.first?.id)
        switch condition { case .all(var values): values.append(value); condition = .all(values); case .any(var values): values.append(value); condition = .any(values); default: break }
    }
    private func remove(_ index: Int) {
        switch condition { case .all(var values): values.remove(at: index); condition = .all(values); case .any(var values): values.remove(at: index); condition = .any(values); default: break }
    }
}

private struct ValidationMessage: View {
    let message: String
    init(_ message: String) { self.message = message }
    var body: some View {
        Label(message, systemImage: "exclamationmark.circle.fill")
            .font(DesignSystem.Typography.uiHint)
            .foregroundStyle(Color(nsColor: .systemRed))
            // The focused banner announces the error context; the inline
            // field message keeps its visible wording for local navigation.
            .accessibilityLabel(message)
    }
}

private extension FieldType {
    var icon: String {
        switch self { case .text: "textformat"; case .richText: "text.justify"; case .audio: "waveform"; case .image: "photo"; case .gif: "sparkles.rectangle.stack"; case .video: "video"; case .number: "number"; case .cloze: "rectangle.dashed" }
    }
}
private extension Interaction {
    var label: String { switch self { case .reveal: "Reveal"; case .type: "Type answer"; case .choose: "Choose"; case .record: "Record"; case .audioSubmission: "Audio Submission"; case .cloze: "Cloze"; case .arrange: "Arrange" } }
}
private extension Modality { var label: String { rawValue == "freeResponse" ? "Free response" : rawValue.capitalized } }
private extension NeoAnkiCore.Operation { var label: String { rawValue.capitalized } }
private extension RevealMode { var label: String { switch self { case .always: "Always visible"; case .hiddenUntilAnswer: "Hidden until answer"; case .blurred: "Blurred until answer" } } }
private extension MediaBehavior { var label: String { switch self { case .default: "Default"; case .autoplay: "Autoplay"; case .playOnTap: "Play on tap"; case .loop: "Loop" } } }
